version: 0.2
phases:
  build:
    commands:
      - apt-get update
      - sudo apt-add-repository ppa:ansible/ansible
      - apt update
      - sudo apt install -y ansible
      - sudo mkdir /root/ansible
      - ls -al /codebuild/output/src[1-9]*/src
      - sudo cp /codebuild/output/src[1-9]*/src/* /root/ansible
      - sudo ansible-playbook -i /root/ansible/hosts /root/ansible/playbook.yaml
artifacts:
  files:
    - install.sh
    - appspec.yml
    - ansible.cfg
    - hosts
    - playbook.yaml
