version: 0.2
phases:
  build:
    commands:
      - apt-get update
      - sudo apt-add-repository ppa:ansible/ansible
      - apt update
      - sudo apt install -y ansible
      - ls -al /codebuild/output/
artifacts:
  files:
    - install.sh
    - appspec.yml
    - ansible.cfg
    - hosts
    - playbook.yaml
