version: 0.2
phases:
  build:
    commands:
      - apt-get update
      - sudo apt-add-repository ppa:ansible/ansible
      - apt update
      - sudo apt install -y ansible
      - sudo ls -al /codebuild/output/src2915263915/src/github.com/georgekcibi/linux-server-patching-using-ansible-and-aws-codepipeline

artifacts:
  files:
    - install.sh
    - appspec.yml
    - ansible.cfg
    - hosts
    - playbook.yaml
